language: node_js
node_js:
  - "9"
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache:
  directories:
    - node_modules
notifications:
  email: false
script:
  - npm run build
  - npm t
